apiVersion: v1
kind: Service
metadata:
  name: django-todo-cluster-ip-service
  namespace: django-todo-ns
spec:
  selector:
    app: django-todo
  type: ClusterIP
  ports:
    - name: http 
      protocol: TCP
      port: 8000
      targetPort: 8000
